# Generated by Django 3.1.7 on 2021-04-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv')),
                ('zip_file', models.FileField(upload_to='zip')),
                ('csv_activated', models.BooleanField(default=False)),
                ('zip_extracted', models.BooleanField(default=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
