# Generated by Django 3.1.7 on 2021-04-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_auto_20210330_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file_name',
            field=models.FileField(upload_to='csv'),
        ),
    ]
