# Generated by Django 3.1.7 on 2021-04-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_imagezipfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagezipfile',
            name='file_name',
            field=models.FileField(upload_to='zip'),
        ),
    ]
