# Generated by Django 3.1.7 on 2021-04-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0007_auto_20210403_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvFile',
        ),
        migrations.DeleteModel(
            name='ImageZipFile',
        ),
    ]
