# Generated by Django 3.1.7 on 2021-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20210401_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='media/profile_pics/default.jpg', null=True, upload_to='media/profile_pics'),
        ),
    ]
