# Generated by Django 3.1.7 on 2021-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_auto_20210402_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv')),
                ('zip_file', models.FileField(upload_to='zip')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
