# Generated by Django 3.1.7 on 2021-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_multiplefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplefiles',
            name='csv_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplefiles',
            name='zip_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
