# Generated by Django 3.1.7 on 2021-04-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20210401_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/profile_pics'),
        ),
    ]
