# Generated by Django 3.1.7 on 2021-04-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20210401_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='/media/default.jpg', null=True, upload_to='static/profile_pics'),
        ),
    ]
